FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Company Demo

Company Demo is a simple API allowing consumers to view companies, add new companies, edit companies
and owners of the companies.

## Company Collection [/companies]

### List All Companies [GET]

You can see all the companies registered in the system by using this action. It retrieves a JSON array
containing the details about each company.

+ Response 200 (application/json)

        [
            {
                "id":"1",
                "name":"first company",
                "address":"some address",
                "city":"city",
                "country":"country",
                "email":null,
                "phoneNumber":null,
                "owners":[
                    {
                        "id":"1",
                        "name":"first owner"
                    }
                ]
            }
        ]

### Create a New Company [POST]

You may create your own company using this action. It takes a JSON
object containing a company and its details.

+ Request (application/json)

        {
            "name":"first company", 
            "address":"some address",
            "city": "city",
            "country": "country"
        }

+ Response 201 (application/json)

    + Body

        {
            "id": 1,
            "name": "first company",
            "address": "some address",
            "city": "city",
            "country": "country",
            "email": null,
            "phoneNumber": null,
            "owners": null
        }